[project]
name = "sber-gigaamv3-local"
version = "0.1.0"
description = ""
authors = [
    {name = "shorins",email = "mighty.shorin@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "transformers==4.57.1",
    "pyannote-audio==4.0.0",
    "torchcodec==0.7.0",
    "gigaam @ git+https://github.com/salute-developers/GigaAM.git",
    "tqdm",
    "python-dotenv",
    "dotenv (>=0.9.9,<0.10.0)"
]

[tool.poetry.dependencies]
torch = [
    {version = "2.8.0", markers = "sys_platform == 'darwin'"},
    {version = "2.8.0", markers = "sys_platform != 'darwin'", source = "pytorch_cuda"}
]
torchaudio = [
    {version = "2.8.0", markers = "sys_platform == 'darwin'"},
    {version = "2.8.0", markers = "sys_platform != 'darwin'", source = "pytorch_cuda"}
]


[[tool.poetry.source]]
name = "pytorch_cuda"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

[tool.poetry]
packages = [{include = "sber_gigaamv3_local", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
